# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit hcinfer.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                      fig.align = "center")
library(hcinfer)
library(ggplot2)
library(dplyr)


## ----workflow, echo=FALSE, fig.cap="Main hcinfer workflow from a fitted lm() object to robust covariance estimation, coefficient inference, and diagnostic graphics. The covariance object provides the robust covariance matrix, leverage values, adjustment factors, and method parameters; the inference object augments these quantities with Wald tests and confidence intervals.", fig.alt="Workflow diagram. A fitted lm() object feeds vcov_hc() and hcinfer(); hcinfer() internally calls vcov_hc(). vcov_hc() returns an hcinfer_vcov object supporting vcov() and plot(); hcinfer() returns an hcinfer object supporting tests(), confint(), summary(), and plot()."----
knitr::include_graphics(
  if (knitr::is_latex_output()) "figures/workflow.pdf" else "figures/workflow.png")


## ----methods, echo=FALSE------------------------------------------------------
methods_df <- data.frame(
  Type = c("hc0", "hc1", "hc2", "hc3", "hc4", "hc4m", "hc5", "hc5m", "hcbeta"),
  Label = c("HC0", "HC1", "HC2", "HC3", "HC4", "HC4m", "HC5", "HC5m", "HCbeta"),
  Description = c(
    "White heteroskedasticity-consistent estimator.",
    "HC0 with degrees-of-freedom scaling.",
    "Leverage-adjusted estimator with exponent 1.",
    "Leverage-adjusted estimator with exponent 2.",
    "Adaptive leverage correction by Cribari-Neto.",
    "Modified HC4 correction by Cribari-Neto and da Silva.",
    "High-leverage correction by Cribari-Neto, Souza, and Vasconcellos.",
    "Modified HC5 correction by Li, Zhang, Zhang, and Wang.",
    "Beta-distribution leverage correction."
  ),
  `Default arguments` = c(
    "none", "none", "none", "none", "none", "none",
    "k = 0.7",
    "k = 0.7, k1 = 1, k2 = 0, k3 = 1, gamma1 = 1, gamma2 = 1.5",
    "c1 = 7, c2 = 0.75, lower = 0.01, upper = 0.99"
  ),
  check.names = FALSE
)
methods_tbl <- knitr::kable(
  methods_df,
  format = if (knitr::is_latex_output()) "latex" else "html",
  booktabs = TRUE,
  caption = "Heteroskedasticity-consistent covariance estimators implemented in the package. The values in the last column are the method-specific defaults exposed through the dots argument of the covariance and inference functions."
)
if (knitr::is_latex_output()) {
  methods_tbl <- kableExtra::column_spec(methods_tbl, 3, width = "5.9cm")
  methods_tbl <- kableExtra::column_spec(methods_tbl, 4, width = "3.7cm")
}
methods_tbl


## ----api, echo=FALSE----------------------------------------------------------
api_df <- data.frame(
  Function = c(
    "hcinfer()", "vcov_hc()", "tests()", "confint()", "summary()",
    "plot()", "hc_methods()", "coef() and vcov()"
  ),
  Role = c(
    "Fits the full robust inference workflow for an lm() object.",
    "Returns the selected HC covariance matrix and diagnostics.",
    "Extracts coefficient-level normal Wald tests as a tibble.",
    "Extracts robust Wald confidence intervals.",
    "Prints model metadata, method parameters, leverage diagnostics, robust weights, tests, and intervals.",
    "Displays confidence intervals for inference objects or adjustment factors against leverage for covariance objects.",
    "Lists implemented estimators and default method-specific arguments.",
    "Extract stored OLS coefficients and robust covariance matrices."
  ),
  check.names = FALSE
)
api_tbl <- knitr::kable(
  api_df,
  format = if (knitr::is_latex_output()) "latex" else "html",
  booktabs = TRUE,
  caption = "Main user-facing functions in hcinfer."
)
if (knitr::is_latex_output()) {
  api_tbl <- kableExtra::column_spec(api_tbl, 2, width = "9.8cm")
}
api_tbl


## ----sandwich-efficiency, echo=FALSE, fig.cap="Factorized covariance data flow in hcinfer. The diagonal is retained as the vector $\\boldsymbol{\\omega}$, and R materializes the row-scaled design $\\operatorname{diag}(\\boldsymbol{\\omega})X$ as an $n \\times p$ temporary before the cross-product returns the middle matrix $M = X'\\operatorname{diag}(\\boldsymbol{\\omega})X$ as $p \\times p$. The upper branch forms $A = X'X$ and a single Cholesky factor, and the two branches meet in four triangular-solve calls, two forward and two backward on matrix right-hand sides, followed by symmetrization of the output. The dashed annotation lists the objects the routine deliberately does not form rather than another step in the flow.", fig.alt="Left-to-right data-flow diagram of the hcinfer covariance calculation. On the left, the inputs are the model matrix X of size n by p, the residual vector, and the weight vector. The flow splits into two branches. The upper branch forms the cross-product A equal to X-transpose times X of size p by p and its Cholesky factor R. The lower branch keeps the weights as the length-n vector omega, materializes the row-scaled design x times omega as an n by p temporary, and returns the middle matrix M equal to X-transpose times diag(omega) times X directly as p by p. The two branches meet only at a solve node that performs four triangular-solve calls on matrix right-hand sides, two forward and two backward, applying the inverse of A twice without storing it, and then symmetrizes the p by p covariance output. Below the flow, a separate dashed box with no arrows into or out of it lists the objects deliberately not formed: the dense n by n diagonal matrix, the explicit transpose of X, the explicit inverse of A, and the p by n product formed by the inverse of A times X-transpose."----
knitr::include_graphics(
  if (knitr::is_latex_output()) "figures/sandwich-efficiency.pdf" else "figures/sandwich-efficiency.png")


## ----architecture, echo=FALSE, fig.cap="Repository-level architecture of hcinfer. The diagram separates the public API, the computational core, the S3 output layer, and the surrounding support files and package assets.", fig.alt="Architecture diagram. A fitted lm() object feeds a user-facing API layer with vcov_hc(), hcinfer(), and hc_methods(). This drives a computational core of model-info.R, hc-weights.R, vcov-hc.R, and hcinfer.R, which produces returned objects and S3 methods: hcinfer_vcov and hcinfer, with vcov(), coef(), tests(), confint(), summary(), print(), and plot(). Supporting infrastructure below covers support files and package assets such as data/, man/, vignettes/, tests/, and docs/."----
knitr::include_graphics(
  if (knitr::is_latex_output()) "figures/architecture.pdf" else "figures/architecture.png")


## ----logo, echo=FALSE, out.width="32%", fig.cap="The hcinfer package logo. The package implements heteroskedasticity-consistent inference for linear models; suggestions and improvements are welcome through GitHub issues and pull requests.", fig.alt="The hcinfer package logo."----
knitr::include_graphics(
  if (knitr::is_latex_output()) "figures/logo.png" else "figures/logo.png")


## ----install, eval=FALSE------------------------------------------------------
# install.packages("hcinfer")
# install.packages("hcinfer", repos = c(
#   "https://prdm0.r-universe.dev",
#   "https://cloud.r-project.org"
# ))
# remotes::install_github("prdm0/hcinfer", force = TRUE)


## ----fit-model----------------------------------------------------------------
library(hcinfer)

data("PublicSchools2", package = "hcinfer")
df <- PublicSchools2
df$scaled_income <- df$income / 10000

fit    <- lm(expenditure ~ scaled_income + scaled_income:south - 1, data = df)
result <- hcinfer(fit)


## ----scatter, echo=FALSE, fig.cap="Scatter plot and fitted regression lines (constrained to pass through the origin) relating annual K-12 per-pupil spending to per capita income for Southern states and the remaining U.S. states.", fig.alt="Scatter plot of expenditure against scaled per capita income. Points are colored by region. Two fitted regression lines, constrained to pass through the origin, are overlaid: one for Southern states and one for the remaining states. The two lines have similar positive slopes over the range of the data."----
ggplot(df, aes(x = scaled_income, y = expenditure)) +
  geom_point(aes(color = factor(south)), alpha = 0.8, size = 2.2) +
  geom_abline(
    intercept = 0,
    slope = coef(fit)["scaled_income"],
    color = "#2c5f8a",
    linewidth = 0.9
  ) +
  geom_abline(
    intercept = 0,
    slope = coef(fit)["scaled_income"] + coef(fit)["scaled_income:south"],
    color = "#c0392b",
    linewidth = 0.9
  ) +
  scale_color_manual(
    name = "Region",
    values = c(`0` = "#7A8896", `1` = "#c0392b"),
    labels = c("0" = "non-South", "1" = "South")
  ) +
  labs(
    x = "Per capita income (scaled by 10,000 USD)",
    y = "K-12 per-pupil expenditure (USD)"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "bottom",
    panel.grid.minor = element_blank()
  )


## ----confint-tests------------------------------------------------------------
confint(result)
tests(result)[c("term", "std_error", "z_value", "p_value")]


## ----intervals, echo=FALSE, fig.cap="HCbeta confidence intervals for the coefficients of the education-expenditure regression (intercept-free model). The vertical dashed line indicates the null value used in the coefficient-level hypothesis tests.", fig.alt="Forest plot of HCbeta confidence intervals for the two regression coefficients. Each row shows a horizontal interval with a point estimate and a vertical dashed line marking the null value used for the Wald tests."----
plot(result)


## ----leverage-----------------------------------------------------------------
cov_hcbeta <- vcov_hc(fit, type = "hcbeta")
h <- cov_hcbeta$leverage
p <- 2
n <- length(h)

# Mild leverage (> 2p/n and <= 3p/n)
unname(which(h > 2 * p / n & h <= 3 * p / n))

# High leverage (> 3p/n)
unname(which(h > 3 * p / n))


## ----plot-cov, fig.show="hide"------------------------------------------------
plot(cov_hcbeta)


## ----weights, echo=FALSE, fig.cap="Adjustment factors $g_t$ versus leverage values $h_t$ for the education-expenditure regression (intercept-free model with an interaction term). Red points correspond to observations whose leverage exceeds the conventional high-leverage threshold of $3p/n$.", fig.alt="Four-panel scatter plot of adjustment factors against leverage for HC3, HC4, HC4m, and HCbeta. Each panel uses a free vertical scale. A dashed vertical line marks the 3p/n high-leverage threshold. Points beyond the threshold are highlighted in red."----
hc_types <- c("hc3", "hc4", "hc4m", "hcbeta")
weights_plot_df <- do.call(rbind, lapply(hc_types, function(tp) {
  obj <- vcov_hc(fit, type = tp)
  data.frame(
    h_t = unname(obj$leverage),
    g_t = unname(obj$weights),
    method = obj$label
  )
}))
weights_plot_df$method <- factor(
  weights_plot_df$method,
  levels = c("HC3", "HC4", "HC4m", "HCbeta")
)
pp <- 2
nn <- length(cov_hcbeta$leverage)
w_threshold <- 3 * pp / nn

ggplot(weights_plot_df, aes(x = h_t, y = g_t)) +
  geom_vline(
    xintercept = w_threshold,
    linewidth = 0.35,
    linetype = "dashed",
    color = "#c0392b"
  ) +
  geom_point(
    aes(color = h_t > w_threshold),
    size = 2.4,
    alpha = 0.9
  ) +
  facet_wrap(~ method, scales = "free_y") +
  scale_color_manual(
    name = NULL,
    values = c(`FALSE` = "#2c5f8a", `TRUE` = "#c0392b"),
    breaks = c(FALSE, TRUE),
    labels = c("regular leverage", "high leverage")
  ) +
  labs(
    x = expression(h[t]),
    y = expression(g[t])
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "bottom",
    panel.grid.minor = element_blank()
  )


## ----comparison, echo=FALSE---------------------------------------------------
hc_all <- c("hc0", "hc1", "hc2", "hc3", "hc4", "hc4m", "hc5", "hc5m", "hcbeta")
hc_labels <- c("HC0", "HC1", "HC2", "HC3", "HC4", "HC4m", "HC5", "HC5m", "HCbeta")

comparison_rows <- lapply(seq_along(hc_all), function(i) {
  tp <- hc_all[i]
  res <- hcinfer(fit, type = tp)
  test_tab <- tests(res)
  ci_tab <- confint(res)
  test_row <- match("scaled_income:south", test_tab$term)
  ci_row <- match("scaled_income:south", ci_tab$term)
  data.frame(
    Estimator = hc_labels[i],
    `Standard error` = sprintf("%.4f", test_tab$std_error[test_row]),
    `p-value` = sprintf("%.4f", test_tab$p_value[test_row]),
    `max g_t` = sprintf("%.4f", max(res$weights)),
    `95% CI` = sprintf(
      "[%.1f, %.1f]",
      ci_tab$conf_low[ci_row],
      ci_tab$conf_high[ci_row]
    ),
    check.names = FALSE
  )
})
comparison_df <- do.call(rbind, comparison_rows)
knitr::kable(
  comparison_df,
  format = if (knitr::is_latex_output()) "latex" else "html",
  booktabs = TRUE,
  caption = "Robust inference for the income-South interaction coefficient in the public school expenditure regression, intercept-free model. The OLS estimate is -322.66, and income is scaled to units of ten thousand U.S. dollars."
)


## ----weights-nodc, echo=FALSE, fig.cap="Adjustment factors $g_t$ plotted against leverage values $h_t$ for the intercept-free model with an interaction term, fitted to the subsample excluding the District of Columbia. Because no observation exceeds the common high-leverage threshold of $3p/n$, the adjustment factors vary more smoothly across the sample, and the plot() method does not highlight any observations in red.", fig.alt="Four-panel scatter plot of adjustment factors against leverage for HC3, HC4, HC4m, and HCbeta fitted on the subsample without the District of Columbia. A dashed vertical line marks the 3p/n threshold; no points are highlighted as high leverage."----
fit_nodc <- lm(
  expenditure ~ scaled_income + scaled_income:south - 1,
  data = df[df$state != "District of Columbia", ]
)
pp_nodc <- 2
nn_nodc <- nobs(fit_nodc)
w_threshold_nodc <- 3 * pp_nodc / nn_nodc

weights_nodc_df <- do.call(rbind, lapply(hc_types, function(tp) {
  obj <- vcov_hc(fit_nodc, type = tp)
  data.frame(
    h_t = unname(obj$leverage),
    g_t = unname(obj$weights),
    method = obj$label
  )
}))
weights_nodc_df$method <- factor(
  weights_nodc_df$method,
  levels = c("HC3", "HC4", "HC4m", "HCbeta")
)

ggplot(weights_nodc_df, aes(x = h_t, y = g_t)) +
  geom_vline(
    xintercept = w_threshold_nodc,
    linewidth = 0.35,
    linetype = "dashed",
    color = "#c0392b"
  ) +
  geom_point(
    aes(color = h_t > w_threshold_nodc),
    size = 2.4,
    alpha = 0.9
  ) +
  facet_wrap(~ method, scales = "free_y") +
  scale_color_manual(
    name = NULL,
    values = c(`FALSE` = "#2c5f8a", `TRUE` = "#c0392b"),
    breaks = c(FALSE, TRUE),
    labels = c("regular leverage", "high leverage")
  ) +
  labs(
    x = expression(h[t]),
    y = expression(g[t])
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "bottom",
    panel.grid.minor = element_blank()
  )


## ----comparison-nodc, echo=FALSE----------------------------------------------
comparison_nodc_rows <- lapply(seq_along(hc_all), function(i) {
  tp <- hc_all[i]
  res <- hcinfer(fit_nodc, type = tp)
  test_tab <- tests(res)
  ci_tab <- confint(res)
  test_row <- match("scaled_income:south", test_tab$term)
  ci_row <- match("scaled_income:south", ci_tab$term)
  data.frame(
    Estimator = hc_labels[i],
    `Standard error` = sprintf("%.4f", test_tab$std_error[test_row]),
    `p-value` = sprintf("%.4f", test_tab$p_value[test_row]),
    `max g_t` = sprintf("%.4f", max(res$weights)),
    `95% CI` = sprintf(
      "[%.1f, %.1f]",
      ci_tab$conf_low[ci_row],
      ci_tab$conf_high[ci_row]
    ),
    check.names = FALSE
  )
})
comparison_nodc_df <- do.call(rbind, comparison_nodc_rows)
knitr::kable(
  comparison_nodc_df,
  format = if (knitr::is_latex_output()) "latex" else "html",
  booktabs = TRUE,
  caption = "Robust inference for the interaction coefficient in the subsample excluding the District of Columbia, intercept-free model. The OLS estimate is -394.79 and the subsample has n = 50 observations."
)


## ----gt-comparison, echo=FALSE------------------------------------------------
fit_intercept <- lm(
  expenditure ~ scaled_income + scaled_income:south,
  data = df
)
gt_rows <- lapply(seq_along(hc_all), function(i) {
  tp <- hc_all[i]
  g_noint <- max(vcov_hc(fit, type = tp)$weights)
  g_int <- max(vcov_hc(fit_intercept, type = tp)$weights)
  data.frame(
    Estimator = hc_labels[i],
    `max g_t (no intercept)` = sprintf("%.2f", g_noint),
    `max g_t (with intercept)` = sprintf("%.2f", g_int),
    check.names = FALSE
  )
})
gt_df <- do.call(rbind, gt_rows)
knitr::kable(
  gt_df,
  format = if (knitr::is_latex_output()) "latex" else "html",
  booktabs = TRUE,
  caption = "Maximum adjustment factor $g_t$ for the interaction coefficient under the intercept-free and intercept models. The intercept-free model is $y_t = \\beta_2 x_{t2} + \\beta_3 x_{t2} x_{t3} + e_t$ and the intercept model is $y_t = \\beta_1 + \\beta_2 x_{t2} + \\beta_3 x_{t2} x_{t3} + e_t$. HCbeta maintains stable adjustment factors across the two specifications."
)

